version: 0.2
env:
    variables:
        S3Bucket: "mailgunwebhookbucket"
        S3Key: "mailgunwebhooklambda.zip"
        LambdaFuncName: MailgunWebhook
phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - echo "Installing dependencies..."
            - npm install -g yarn
            - cd lambda-node
            - yarn install
    build:
        commands:
            - echo "Building Typecript project and zipping file for s3 upload for lambda function to have access"
            - yarn build-zip
    post_build:
        commands:
            - echo "Uploading/Updating files in the S3 bucket..."
            - aws s3 cp ./$S3Key  s3://$S3Bucket
            - echo "Updating Lambda Function with uploaded zip file in s3..."
            - aws lambda update-function-code --function-name $LambdaFuncName --s3-bucket $S3Bucket --s3-key $S3Key
