AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MailGunSigningKey:
    Type: String
    # add mailgun http webhook signing key here
    Default: ""
  SNSSubscriptionEmail:
    Type: String
    # add email here to receive the SNS notification when mailgun webhook is received.
    Default: ""
  SNSTopicName:
    Type: String
    Default: MailGunWebHookEvents2
  LambdaFuncName:
    Type: String
    Default: MailgunWebHook2
  DynamoDBTableName:
    Type: String
    Default: MailGunWebHookEvents2
  APIName:
    Type: String
    Default: MailGunWebHook2
  APIResourcePath:
    Type: String
    Default: mailgunwebhook
  EnvironmentName:
    Type: String
    Default: dev
  AWSRegionSelected:
    Type: String
    Default: ap-southeast-1
  S3Bucket:
    Type: String
    Default: mailgunwebhookbucket2
  S3Key:
    Type: String
    Default: mailgunwebhooklambda.zip

Resources:
  SNSPublish:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        - Endpoint: !Ref SNSSubscriptionEmail
          Protocol: email
      TopicName:
        Ref: SNSTopicName
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      FunctionName:
        Ref: LambdaFuncName
      Handler: index.handler
      Runtime: nodejs16.x
      Role: !GetAtt IAMRole.Arn
      Environment:
        Variables:
          AWS_REGION_SELECTED: !Ref AWSRegionSelected
          DYNAMO_DB_TABLE_NAME: !Ref DynamoDBTableName
          SIGNING_KEY: !Ref MailGunSigningKey
          SNS_TOPIC_ARN: !Sub
            - >-
              arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${TopicName}
            - TopicName: !Ref SNSTopicName
    DependsOn:
      - DynamoDBTable
      - SNSPublish
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName:
        Ref: DynamoDBTableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: date
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  APIGatewayRestAPI:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name:
        Ref: APIName
      Parameters:
        endpointConfigurationTypes: REGIONAL
    DependsOn:
      - LambdaFunction
  APIGatewayResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ParentId: !GetAtt
        - APIGatewayRestAPI
        - RootResourceId
      PathPart:
        Ref: APIResourcePath
    DependsOn:
      - APIGatewayRestAPI
  APIGatewayMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ResourceId: !Ref APIGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
      Integration:
        Type: AWS_PROXY
        IntegrationResponses:
          - StatusCode: 200
        IntegrationHttpMethod: POST
        Uri: !Sub
          - >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFuncNameArn}/invocations
          - LambdaFuncNameArn: !GetAtt LambdaFunction.Arn
    DependsOn:
      - APIGatewayResource
  APIGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      StageName:
        Ref: EnvironmentName
    DependsOn:
      - APIGatewayMethod
  APIGatewayPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: apigateway.amazonaws.com
    DependsOn:
      - APIGatewayDeployment
  IAMRole:
    Type: "AWS::IAM::Role"
    DependsOn:
      - SNSPublish
      - DynamoDBTable
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: Policy_api-lambda-db
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:BatchWriteItem"
                  - "dynamodb:TagResource"
                  - "dynamodb:UntagResource"
                  - "dynamodb:PutItem"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:UpdateItem"
                Resource: !GetAtt DynamoDBTable.Arn
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:CreateLogGroup"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "sns:*"
                Resource: !Sub
                  - >-
                    arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${TopicName}
                  - TopicName: !Ref SNSTopicName
              - Effect: Allow
                Action:
                  - "s3:*"
                Resource: !Sub
                  - >-
                    arn:aws:s3:::${BucketName}
                  - BucketName: !Ref S3Bucket
