AWSTemplateFormatVersion: "2010-09-09"
# *** Change this to something useful for you!
Description: github-codebuild

Parameters:
  # *** This value must always be passed in when creating / updating stack
  # "NoEcho" is set to true, for security, so token won't be visible when examining the resulting stack
  GitHubOAuthToken:
    Type: String
    NoEcho: true
    MinLength: 93
    MaxLength: 93
    AllowedPattern: "[A-Za-z0-9_]*"

  # *** The remaining parameters should either be:
  # - overridden via changing "Default" here (PREFERABLE, since then they're in source control)
  # - or you can pass them in when creating / updating the stack

  # *** The owner of the Github repo for this application.
  GitHubRepoOwner:
    Type: String
    Default: niccololampa

  GitHubRepo:
    Type: String
    Default: mailgun-webhook-aws-api-dynamodb-sns

  GitHubBranch:
    Type: String
    Default: feature/codebuild

  S3Bucket:
    Type: String
    Default: mailgunwebhookbucket3

  CodeBuildName:
    Type: String
    Default: MailGunWebHookEvents3

Resources:
  S3LambdaBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3Bucket

  LambaNodeCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildName
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GitHubRepoOwner}/${GitHubRepo}.git
        GitCloneDepth: 1
        BuildSpec: lambda-node/buildspec.yml
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              # Pattern: ^refs/heads/feature/.*
              Pattern: !Sub ^refs/heads/${GitHubBranch}
              # Pattern: ^refs/heads/master
      Environment:
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:2.0
        ComputeType: BUILD_GENERAL1_SMALL
      ServiceRole: !GetAtt LambdaNodeCodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Sub ${CodeBuildName}-CloudWatchLogs-BuildLogGroup-Name
    DependsOn:
      - LambdaNodeCodeBuildRole
      - S3LambdaBucket

  LambdaNodeCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: PolicyCodebuild
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - codebuild:*
                  - logs:*
                Resource: "*"
